import test from 'node:test';
import assert from 'node:assert/strict';
import {createFleet,resolveTarget,validServerId} from '../server/fleet.mjs';
const id=n=>'srv-'+String(n).padStart(24,'0');
const profile=n=>({id:id(n),host:`192.0.2.${n}`,name:`Server ${n}`,platform:n===1?'linux':'windows',status:'ready',capabilities:{storage:true}});
function fixture(){const calls={created:[],scanned:[],closed:[]};return {calls,fleet:createFleet({dataDir:'test-data',inventoryFactory:config=>{calls.created.push(config);return {dataDir:config.dataDir,initialize:async()=>{},inventory:()=>({apps:[],serverId:config.id,scannedAt:null,unread:0}),scheduledScan:()=>calls.scanned.push(config.id),shutdown:async()=>calls.closed.push(config.id)};}})};}
test('clean installation has no default server or network discovery',async()=>{const {fleet,calls}=fixture();await fleet.initialize();assert.equal(fleet.primary,null);assert.deepEqual(fleet.list().servers,[]);fleet.tick();assert.deepEqual(calls.created,[]);assert.deepEqual(calls.scanned,[]);await fleet.shutdown();});
test('only registered ready targets enter fleet, maintain platform and isolated paths',async()=>{const {fleet,calls}=fixture();await fleet.add({...profile(3),status:'installing'});await fleet.add(profile(1));await fleet.add(profile(2));await fleet.add(profile(1));assert.equal(calls.created.length,2);assert.notEqual(calls.created[0].dataDir,calls.created[1].dataDir);assert.equal(calls.created[1].platform,'windows');assert.deepEqual(fleet.list().servers.map(s=>s.id),[id(1),id(2)]);fleet.tick();assert.deepEqual(calls.scanned,[id(1),id(2)]);await fleet.remove(id(1));assert.throws(()=>fleet.resolve(id(1)),{status:404});assert.equal(fleet.primary.dataDir,calls.created[1].dataDir);await fleet.shutdown();assert.deepEqual(calls.closed,[id(1),id(2)]);});
test('server resolution cannot use arbitrary aliases, addresses or traversal',()=>{const target={};const map=new Map([[id(1),target]]);assert.equal(resolveTarget(map,id(1)),target);for(const value of ['localhost','192.0.2.1','../a','__proto__','srv-a',id(2),undefined])assert.throws(()=>resolveTarget(map,value),{status:404});assert.equal(validServerId(id(1)),true);});
