import { launcherActions, matchesSearch, type LaunchItem } from './launcher-data';

export const featureCategories = ['Başlangıç', 'İzleme', 'Yönetim', 'Dosyalar', 'Çalışma alanı'] as const;
export type FeatureCategory = typeof featureCategories[number];
export type FeatureChapter = {
  id: string; category: FeatureCategory; item: LaunchItem; summary: string; when: string;
  steps: string[]; notes: string[]; related: string[];
};
function chapter(id: string, category: FeatureCategory, summary: string, when: string, steps: string[], notes: string[], related: string[] = []): FeatureChapter {
  const item = id === 'folder:/' ? {id,kind:'folder' as const,path:'/',label:'Dosya Gezgini'}
    : id === 'trash' ? {id,kind:'trash' as const,label:'Çöp kutusu'}
    : launcherActions.find(action => action.id === id);
  if (!item) throw new Error(`Unknown guide destination: ${id}`);
  return {id,category,item,summary,when,steps,notes,related};
}
export const featureChapters: FeatureChapter[] = [
  chapter('action:servers','Başlangıç',
    'Sunucularınızı bağladığınız, bağlantı durumunu gördüğünüz ve yönetmek istediğiniz hedefi seçtiğiniz ekran.',
    'Yeni bir Windows veya Linux sunucusu eklemek ya da çalışma alanını başka bir sunucuya geçirmek istediğinizde.',
    ['Sunucu ekle ile işletim sistemini, adresi ve SSH portunu belirtin.', 'Sunucunun anahtar parmak izini güvenilir bir kaynaktan doğrulayın; kullanıcı ve kimlik doğrulama bilgilerini girin.', 'Kurulum adımlarını ve desteklenen özellikleri inceleyip sunucuyu seçin.'],
    ['İşlemler seçili sunucuya uygulanır. ViiOS giriş şifresi ile sunucunun SSH şifresi farklıdır.', 'Windows hedefinde uygun OpenSSH erişimi gerekir. Bağlantıyı kaldırmak uzak sunucudaki dosyaları silmez.'], ['action:overview','applications']),
  chapter('applications','Başlangıç',
    'Keşfedilen uygulamaları, alt projelerini, servislerini ve portlarını tek yerde toplar.',
    'Hangi uygulamaların çalıştığını ve onlara nereden erişeceğinizi öğrenmek istediğinizde.',
    ['Bir uygulamayı seçerek bağlı servislerini, portlarını ve ayrıntılarını açın.', 'Mevcutsa önizleme, dosyalar, repo veya işlem geçmişi bağlantılarına geçin.', 'Desteklenen yönetim işlemlerinde başlatma, durdurma veya yeniden başlatma adımını inceleyip onaylayın.'],
    ['Uygulama listesi seçili sunucunun keşif sonuçlarından oluşur; sabit bir uygulama mağazası değildir.', 'Yerel test uygulaması, bu akışı denemek için oluşturulmuş örnek bir web servisidir.'], ['action:endpoints','action:credentials','tasks']),
  chapter('action:features','Başlangıç',
    'ViiOS uygulamalarını bir kitapçık gibi okuyabileceğiniz, arayıp karşılaştırabileceğiniz özellik kütüphanesi.',
    'Bir simgenin ne işe yaradığını öğrenmek veya doğru aracı bulmak istediğinizde.',
    ['İçindekilerden bir uygulama seçin veya arama alanına bir konu yazın.', 'Kullanım adımlarını ve sınırları okuyun; ilgili uygulamayı aç düğmesiyle araca geçin.'],
    ['Rehber, mevcut özellikleri anlatır. Bir özelliğin kullanılabilmesi seçili sunucunun yetenek ve izinlerine bağlıdır.'], ['action:help','action:guide']),
  chapter('action:help','Başlangıç',
    'Sunucu bağlama, dosya erişimi ve temel yönetim akışları için kısa başlangıç rehberi.',
    'ViiOS’u ilk kez kullanırken temel işlemlerin sırasını öğrenmek istediğinizde.',
    ['Sunucu bağlama ve uygulama keşfi açıklamalarını okuyun.', 'Bölümlerdeki düğmelerle Sunucular, Uygulamalar, Dosyalar veya Depolama ekranına geçin.'],
    ['Bu ekran hızlı başlangıç içindir. Araçların ayrıntılı açıklamaları Özellik Rehberi’nde bulunur.'], ['action:servers','action:features']),
  chapter('action:guide','Başlangıç',
    'Pencereleri, Dock’u, masaüstü kısayollarını ve klavye kullanımını anlatan çalışma alanı rehberi.',
    'Pencereleri taşımak, küçültmek, kısayol eklemek veya arama kullanmak istediğinizde.',
    ['Pencere başlığından taşıyın, köşeden boyutlandırın; başlık düğmeleriyle küçültün veya büyütün.', 'Dock’taki + düğmesinden kısayolları düzenleyin. Dar ekranda oklarla diğer uygulamalara geçin.', 'Ctrl + K ile uygulama ve dosya aramasını açın.'],
    ['Kısayol düzeni seçili sunucuya kaydedilir. Küçültmek açık dosyadaki taslağı korur.', 'Rehberdeki dosya işlemleri yalnız hedef sunucu bunları destekliyorsa kullanılabilir.'], ['action:appearance','folder:/']),
  chapter('action:overview','İzleme',
    'Sunucunun genel sağlık ve kaynak durumunu tek bakışta gösterir: CPU, RAM, takas alanı, disk, ağ ve çalışma süresi.',
    'Sunucu yavaşladığında genel durumu görmek veya hangi kaynağın yoğun olduğunu anlamak istediğinizde.',
    ['Sunucu Monitörü’nü açıp seçili sunucunun kimliğini ve son ölçüm zamanını kontrol edin.', 'CPU, bellek, disk ve ağ ölçümlerini birlikte değerlendirin.', 'Kaynak tüketen süreçleri incelemek için Süreç Yöneticisi’ne geçin.'],
    ['Ölçüm alınamayan değerler — olarak gösterilir; bu, kullanımın sıfır olduğu anlamına gelmez.', 'Sıcaklık ve bazı ölçümler işletim sistemine veya donanım desteğine bağlıdır.'], ['action:processes','action:storage','tasks']),
  chapter('action:processes','İzleme',
    'İşletim sistemi süreçlerini PID, ad, CPU, bellek ve erişilebilen diğer ayrıntılarıyla listeler.',
    'Kaynak tüketen bir süreci bulmak ya da belirli bir sürecin ayrıntısını incelemek istediğinizde.',
    ['Süreç adı veya PID ile arayın; CPU ya da bellek sütununa göre sıralayın.', 'Süreç ayrıntısını açıp kimliğini ve durumunu kontrol edin.', 'Sonlandırma sunuluyorsa etkisini inceleyerek onaylayın.'],
    ['Korumalı veya izin verilmeyen süreçler sonlandırılamaz. İşlem öncesinde süreç kimliği yeniden doğrulanır.', 'Server-Lab test hedefinde yalnızca deneme için oluşturulan süreç sonlandırılabilir.'], ['action:overview','action:services']),
  chapter('tasks','İzleme',
    'Keşfedilmiş uygulamalar ve portlarla ilişkili kaynak kullanımını gösteren mevcut Görev Yöneticisi.',
    'Kaynak tüketimini ViiOS’taki uygulama ve portlarla birlikte değerlendirmek istediğinizde.',
    ['Uygulama adı, port veya PID ile arama yapın.', 'CPU ve RAM değerlerini karşılaştırın; uygulama ayrıntısına veya Depolama’ya geçin.'],
    ['Süreç Yöneticisi işletim sistemi süreçlerini, Görev Yöneticisi ise uygulama odaklı kaynak görünümünü sunar.', 'Ölçümü duraklatmak uygulamaları durdurmaz.'], ['action:processes','applications','action:storage']),
  chapter('action:storage','İzleme',
    'Diskleri, bölümleri, kapasiteyi ve izin verilen klasörlerle uygulamaların alan kullanımını gösterir.',
    'Disk dolduğunda alanı hangi bölüm, klasör veya uygulamanın kullandığını araştırmak istediğinizde.',
    ['Diskler ve I/O sekmesinde fiziksel diskleri, bağlı bölümleri ve okuma/yazma ölçümlerini inceleyin.', 'Disk bölümlerinden kullanılabilir alanı kontrol edin; Klasörleri incele ile bir konumu tarayın.', 'Klasörler ve Uygulamalar sekmelerindeki dağılıma bakın; gerektiğinde Dosya Gezgini’ne geçin.'],
    ['Fiziksel disk, bölüm ve mantıksal katman boyutlarını toplamak kapasiteyi iki kez sayabilir.', 'Bir bölümün boş alanı başka bir bölümün doluluğunu gidermez. Kısmi taramalar tam toplam değildir.', 'Server-Lab’de disk ölçümleri gerçektir; klasör ve dosya incelemesi örnek dosya alanıyla sınırlıdır.'], ['folder:/','action:overview']),
  chapter('action:endpoints','İzleme',
    'Sunucuda keşfedilen portları, yanıt durumlarını, erişim adreslerini ve denetim notlarını listeler.',
    'Belirli bir portun hangi uygulamaya ait olduğunu ve nasıl yanıt verdiğini incelemek istediğinizde.',
    ['Port veya uygulama adına göre arayın ve filtreleri kullanın.', 'Bir kaydı seçip önizlemesini, protokolünü ve son kontrol bilgisini inceleyin.', 'Gerektiğinde not ekleyin veya ilgili portun işlem geçmişini açın.'],
    ['401, 403 veya 404 yanıtı tek başına servisin kapalı olduğunu göstermez.', 'Sonuçlar son keşfe aittir; güncel durumu gerektiğinde yeniden tarayın.'], ['applications','action:ports','action:history']),
  chapter('action:ports','İzleme',
    'Son ölçümde dinleyici bulunmayan portları protokol ve aralık filtreleriyle araştırır.',
    'Yeni bir uygulama için aday port aradığınızda.',
    ['İlgili port aralığını ve protokol filtresini seçin.', 'Son tarama zamanına ve varsa eski kullanım bilgisine bakın.'],
    ['Boş görünen port rezerve edilmez; uygulama başlarken başka bir süreç tarafından alınabilir.', 'Yalnız ağ üzerinden yanıt gelmemesi, portun boş olduğunu kanıtlamaz. Sunucu erişimi gerekir.'], ['action:endpoints','action:servers']),
  chapter('action:services','Yönetim',
    'İşletim sistemi servislerini ve desteklenen servis işlemlerini tek ekranda sunar.',
    'Bir servisin çalışıp çalışmadığını görmek, ayrıntılarını okumak veya izinli yönetim işlemlerini yapmak istediğinizde.',
    ['Servis adıyla arayın, duruma göre filtreleyin ve servis ayrıntısını açın.', 'Başlangıç türünü ve varsa günlükleri inceleyin.', 'Sunulan başlat, durdur veya yeniden başlat işlemini onay adımıyla uygulayın.'],
    ['İşlemler işletim sistemine, izinlere ve servis korumalarına bağlıdır; her servis değiştirilemez.', 'Server-Lab’de gerçek Windows servisleri görüntülenir. Yönetim denemesi ViiOS Lab Service adlı ayrı test süreci üzerinde yapılır.'], ['action:processes','action:history']),
  chapter('action:models','Yönetim',
    'Desteklenen model çalışma ortamlarını, bulunan modelleri ve mevcut kullanım bilgilerini bir araya getirir.',
    'Hangi modellerin bulunduğunu, hangilerinin çalıştığını ve erişim durumlarını araştırmak istediğinizde.',
    ['Model kataloğunu açıp son tarama ve bağlantı durumunu inceleyin.', 'Bir modelin çalışma ortamına, boyutuna, adresine ve keşif bilgilerine bakın.', 'Sunulan kullanım veya kıyaslama araçlarını hedefin desteklediği ölçüde kullanın.'],
    ['Modelin listelenmesi, o anda çalıştığı anlamına gelmez; durum etiketini kontrol edin.', 'Keşif ve ölçüm kapsamı desteklenen çalışma ortamlarına ve erişim izinlerine bağlıdır.'], ['applications','action:overview']),
  chapter('action:credentials','Yönetim',
    'Uygulamaların yönetim paneli adreslerini, kullanıcı adlarını ve kaydedilmiş erişim bilgilerini bir arada tutar.',
    'Bir uygulamanın yönetim ekranını bulmak veya kaydedilmiş giriş bilgisini kullanmak istediğinizde.',
    ['Uygulama kaydını bulun; yönetim paneli bağlantısından ilgili adrese gidin.', 'Kayıtlı bilgileri gerektiğinde görüntüleyin veya kopyalayın; düzenleme ile güncelleyin.'],
    ['Kayıtlı değil ifadesi, bilgiyi henüz saklamadığınızı belirtir; bir şifre tahmini değildir.', 'Bu kayıtlar ViiOS yönetici girişinden ve sunucu bağlantı kimlik bilgilerinden ayrıdır.'], ['applications','action:servers']),
  chapter('action:people','Yönetim',
    'Proje ve uygulama ekipleriyle ilişkilendirebileceğiniz kişi kayıtlarını yönetir.',
    'Uygulamaların kimlerle ilişkili olduğunu düzenlemek istediğinizde.',
    ['Kişi ekleyin veya mevcut kişinin adını düzenleyin.', 'Uygulama ve proje ekiplerinde ilgili kişileri seçin.'],
    ['Kişi kaydı oluşturmak işletim sistemi kullanıcısı veya ViiOS giriş hesabı oluşturmaz.'], ['applications','repo']),
  chapter('folder:/','Dosyalar',
    'Seçili sunucunun izin verdiği dosya ve klasörleri masaüstü penceresinde açar.',
    'Dosya içeriğini görmek veya desteklenen dosya işlemlerini yapmak istediğinizde.',
    ['Sunucunun sunduğu kök konumlardan birini seçip klasörlere ilerleyin.', 'Dosyayı açın veya özelliklerinden boyut, tarih ve izin bilgilerini inceleyin.', 'Yazma yetkisi ve hedef desteği varsa düzenleme, taşıma ve aktarım araçlarını kullanın.'],
    ['Windows yolları /C: gibi sanal sürücü yollarıyla gösterilebilir.', 'Server-Lab örnek dosya alanı salt okunurdur; gerçek sunucularda da işletim sistemi ve klasör izinleri geçerlidir.'], ['action:storage','trash','action:versions']),
  chapter('trash','Dosyalar',
    'Desteklenen dosya işlemleriyle ViiOS çöp kutusuna taşınan öğeleri gösterir.',
    'ViiOS üzerinden çöp kutusuna aldığınız bir öğeyi incelemek veya geri yüklemek istediğinizde.',
    ['Çöp kutusunu açıp sunucunun sunduğu kayıtları inceleyin.', 'Desteklenen geri yükleme işlemiyle öğeyi eski konumuna taşıyın.'],
    ['Bu ekran bütün işletim sisteminin tüm kullanıcılarına ait çöp kutularını birleştirmez.', 'Geri yükleme, yazma izni ve hedef desteği gerektirir; Server-Lab dosya değişikliklerine izin vermez.'], ['folder:/']),
  chapter('repo','Dosyalar',
    'Desteklenen sunuculardaki Git depolarını, değişiklikleri ve sürüm geçmişini incelemek için kullanılan merkez.',
    'Bir projenin hangi dosyalarının değiştiğini ve Git geçmişini görmek istediğinizde.',
    ['Repo Merkezi’nden bir depo seçin veya desteklenen akışla depo ekleyin.', 'Dallar, commit geçmişi ve dosya farklarını inceleyin.', 'Yalnız sunulan ve yetkinizin bulunduğu kayıt veya geri alma işlemlerini uygulayın.'],
    ['Git ve sürüm desteği olmayan sunucularda kullanılamaz. Server-Lab test hedefinde pasiftir.', 'Git işlemleri ile çalışan servisi yeniden başlatmak ayrı işlemlerdir.'], ['action:versions','folder:/']),
  chapter('action:versions','Dosyalar',
    'Desteklenen dosya ve klasörler için sürüm geçmişi, karşılaştırma ve geri yükleme araçlarını açar.',
    'Bir değişikliği önceki hâliyle karşılaştırmak veya uygun bir sürüme dönmek istediğinizde.',
    ['Sürüm Yönetimi’ni açıp ilgili konumu ve sürümü seçin.', 'Farkları inceleyin; geri yükleme sunuluyorsa etkisini kontrol ederek onaylayın.'],
    ['Sunucunun sürüm desteği ve hesap izinleri gerekir. Server-Lab test hedefinde kullanılamaz.', 'Açık dosyalardaki kaydedilmemiş değişiklikleri önce ele alın. Bu araç tüm sunucunun otomatik yedeği değildir.'], ['repo','folder:/']),
  chapter('action:history','Çalışma alanı',
    'ViiOS’un tarama, port durumu ve yönetim işlemleriyle ilgili kalıcı olay geçmişini gösterir.',
    'Ne zaman bir port açıldı, kapandı veya bir işlem hata verdi diye araştırdığınızda.',
    ['Olay türü ve tarih aralığıyla kayıtları filtreleyin.', 'Uygulama veya port bağlantısından ilgili ayrıntıya geçin; gerekirse CSV raporu alın.'],
    ['İşlem geçmişi, ViiOS olaylarını içerir. Henüz geliştirilmemiş merkezi sistem/uygulama günlük ekranının yerine geçmez.'], ['action:notifications','action:reports']),
  chapter('action:notifications','Çalışma alanı',
    'ViiOS’un dikkat gerektiren olaylarını ve okunmamış bildirimlerini bir araya getirir.',
    'Bağlantı sorunları veya durum değişiklikleri gibi uyarıları gözden geçirmek istediğinizde.',
    ['Bildirimleri uygulamaya veya olay türüne göre inceleyin.', 'İlgili uygulamaya geçin ve incelediğiniz bildirimleri okundu olarak işaretleyin.'],
    ['Okundu işaretlemek temel sorunu çözmez; yalnız bildirim durumunu değiştirir.'], ['action:history','applications']),
  chapter('action:reports','Çalışma alanı',
    'Sunucu envanteri, olaylar ve desteklenen port bilgileri için dışa aktarılabilir raporlar sunar.',
    'Mevcut durumu belgelemek veya verileri başka bir araçta incelemek istediğinizde.',
    ['Rapor türünü ve sunulan filtreleri seçin.', 'Desteklenen CSV veya JSON biçimini indirip raporun zaman ve sunucu bilgisini kontrol edin.'],
    ['Raporlar ilgili ölçüm ve kayıtlara dayanır; anlık bir canlı ekran veya sunucu yedeği değildir.'], ['action:endpoints','action:history']),
  chapter('action:appearance','Çalışma alanı',
    'Açık/koyu tema ile kilit ekranı ve masaüstü duvar kâğıdını kişiselleştirir.',
    'Çalışma alanının renklerini ve görünümünü değiştirmek istediğinizde.',
    ['Görünüm’den açık veya koyu temayı seçin.', 'Kilit ekranı ve masaüstü için duvar kâğıdını ayrı ayrı belirleyin.'],
    ['Masaüstü seçimi uygulama vurgu renklerini de etkiler. Bu tercihler tarayıcıda saklanır.', 'Dock’taki kısayolları ve sıralamayı değiştirmek için + düğmesini kullanın.'], ['action:guide']),
];
export function filterFeatures(query: string, category: FeatureCategory | 'Tümü') {
  return featureChapters.filter(entry => (category === 'Tümü' || entry.category === category) && matchesSearch([entry.item.label,entry.summary,entry.when,...entry.steps,...entry.notes].join(' '),query));
}
