'use client';
import { Activity, BookOpen, FolderOpen, HardDrive, History, Network, Server, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
export default function HelpPanel({ onGo }: { onGo: (view: 'apps' | 'managed' | 'ports' | 'reports' | 'files' | 'servers' | 'storage') => void }) {
  return <section className="help-panel">
    <div className="help-intro"><span><BookOpen size={26}/></span><div><h2>ViiOS kullanım rehberi</h2><p>Windows ve Linux sunucularınızı aynı çalışma alanından yönetin.</p></div></div>
    <div className="help-grid">
      <article><Server/><h3>Sunucu bağlayın</h3><p><b>ViiOS → Sunucular → Sunucu ekle</b> yolunu izleyin. Hedef işletim sistemini seçin; IP veya sunucu adını ve SSH portunu girin.</p><p>Gösterilen SSH parmak izini sunucunun güvenilir konsolundan doğrulayın. Ardından kullanıcı adını, şifreyi veya özel anahtarı girin. Linux’ta kurulum için gerekiyorsa sudo şifresi ekleyin. Windows hedefinde OpenSSH Server etkin olmalıdır.</p><p>Kurulum adımları ve sonuçta kullanılabilen özellikler Sunucular ekranında görünür. Bağlantıyı kaldırmak yalnızca yerel ViiOS kaydını kaldırır; uzaktaki dosyaları silmez.</p><Button variant="outline" onClick={() => onGo('servers')}>Sunucuları aç</Button></article>
      <article><Network/><h3>Uygulamaları ve portları görün</h3><p>Uygulamalar ekranı seçili sunucunun servislerini ve portlarını bir araya getirir. Bir uygulamayı seçerek erişim adresini, sürecini, port geçmişini ve mevcut yönetim işlemlerini inceleyin.</p><p>401, 403 veya 404 yanıtı tek başına servisin çalışmadığını göstermez. “Boş port”, son ölçümde dinleyici bulunmadığını belirtir; portu sizin için ayırmaz.</p><p>Notlar, favoriler ve günlükler sunucuya özeldir. Sunucu seçtiğinizde tüm araçlar seçilen hedefe geçer.</p><Button variant="outline" onClick={() => onGo('apps')}>Uygulamaları aç</Button></article>
      <article><FolderOpen/><h3>Dosyalara ulaşın</h3><p>Dosya Gezgini, sunucunun izin verdiği konumları gösterir. Windows sürücüleri <code>/C:</code> gibi sanal yollarla, Linux dizinleri kendi yollarıyla görünür. Ana konum sunucudan alınır.</p><p>Desteklenen işlemlerde dosya ve klasörleri açabilir, düzenleyebilir, kopyalayabilir veya taşıyabilirsiniz. İçe ve dışa aktarma özellikleri bağlantının yeteneklerine bağlıdır. Korumalı alanlarda işlemler kısıtlanır.</p><p>Başlık çubuğu pencereleri taşır; köşe tutamaçları boyutlandırır. Küçültülen bir dosya penceresi taslağını korur. Başlat veya <b>Ctrl + K</b> ile uygulama ve dosya arayın.</p><Button variant="outline" onClick={() => onGo('files')}>Dosyaları aç</Button></article>
      <article><HardDrive/><h3>Depolamayı inceleyin</h3><p>Depolama ekranı tüm bağlı disk bölümlerini, kullanılan alanı, kullanılabilir alanı ve sisteme ayrılan alanı gösterir. Bir bölümdeki doluluk başka bir bölümün boş olmasıyla azalmaz.</p><p><b>Klasörleri incele</b> ile büyük klasörlere ilerleyin. Uygulamalar sekmesi bilinen proje klasörlerinin boyutlarını gösterir. Ortak klasörler aynı dosyaları içerebildiği için uygulama boyutları toplanmamalıdır.</p><p>“En az” kısmi ölçümü, “—” ölçüm alınamadığını belirtir. Yeni bir klasör taraması büyük dizinlerde zaman alabilir.</p><Button variant="outline" onClick={() => onGo('storage')}>Depolamayı aç</Button></article>
      <article><Activity/><h3>Kaynakları ve desteklenen özellikleri izleyin</h3><p>Görev Yöneticisi sunucunun CPU, bellek ve disk ölçümlerini gösterir. Ölçüm alınamayan değerler sıfır olarak sunulmaz.</p><p>Dosya işlemleri, servis yönetimi, Git ve model keşfi; hedef işletim sistemi, kurulu bileşenler ve hesap izinlerine göre değişir. Sunucular ekranındaki özellik listesi destek durumunu gösterir. Bir işlemin kullanılamama nedeni ilgili araçta görünür.</p></article>
      <article><History/><h3>Değişiklikleri takip edin</h3><p>Port günlüğü açılma, kapanma ve yapılan işlemleri gösterir. Raporlar bölümünde desteklenen envanter ve günlükleri CSV veya JSON olarak dışa aktarabilirsiniz.</p><p>ViiOS’un bu bilgisayardaki denetleyicisi çalıştığı sürece bağlantılar ve izleme etkin kalır. Yönetici şifresi bu kuruluma aittir; sunucuların SSH şifrelerinden ayrıdır.</p><Button variant="outline" onClick={() => onGo('reports')}>Raporları aç</Button></article>
    </div>
    <div className="help-bottom"><h3><ShieldCheck size={18}/> Bağlantı kimliği ve oturum</h3><p>Sunucunun SSH anahtarı değişirse bağlantı otomatik olarak güvenilir sayılmaz. Yeni parmak izini doğrulayın. Yönetici oturumunu kapatmak için masaüstü menüsünü kullanın. Görünüm seçimleriniz bu tarayıcıda saklanır.</p></div>
  </section>;
}
