'use client';
import { useTarget } from './target-context';
import { useState } from 'react';
import { ArrowUpRight, Code2, History, Search, Settings2, X } from 'lucide-react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import ControlActions, { canManage } from './control-actions';
import type { App, ControlAction, Inventory } from './types';

export default function ManagedApps({inventory,busy,onAction,onSelect,onHistory,onScan}:{inventory:Inventory|null;busy:boolean;onAction:(app:App,action:ControlAction)=>void;onSelect:(app:App)=>void;onHistory:(port:number)=>void;onScan:()=>void}) {
  const {url}=useTarget();
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const managed=(inventory?.apps || []).filter(canManage);
  const running=managed.filter(a=>a.active!==false).length,stopped=managed.length-running;
  const visible=managed.filter(app=>(filter==='all' || (filter==='running'?app.active!==false:app.active===false)) && `${app.port} ${app.name} ${app.control?.label || ''} ${app.annotation?.tags.join(' ') || ''}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')));
  return <section className="managed-apps"><div className="managed-intro"><span className="managed-icon"><Settings2 size={24}/></span><div><h2>Yönetilebilir uygulamalar <span>{managed.length}</span></h2><p>Her uygulamanın yanında Başlat, Durdur ve Yeniden başlat seçenekleri bulunur.</p></div></div><div className="managed-toolbar"><div className="filter-group">{[{value:'all',label:'Tümü',count:managed.length},{value:'running',label:'Çalışan',count:running},{value:'stopped',label:'Kapalı',count:stopped}].map(item=><Button key={item.value} variant="ghost" className={`filter ${filter===item.value?'active':''}`} aria-pressed={filter===item.value} onClick={()=>setFilter(item.value)}>{item.label}<span>{item.count}</span></Button>)}</div><div className="search-field"><Search size={16}/><Input aria-label="Yönetilebilir uygulama ara" placeholder="Uygulama, port veya servis ara…" value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button aria-label="Yönetilebilir uygulama aramasını temizle" onClick={()=>setQuery('')}><X size={14}/></button>}</div></div>
  {inventory?.controlError && <div className="notice error-notice" role="alert"><Settings2 size={18}/><span>{inventory.controlError}</span><Button variant="outline" onClick={onScan}>Tekrar tara</Button></div>}
  {inventory?.error && <div className="notice error-notice">Son başarılı tarama gösteriliyor; sunucuya yeniden bağlanılması bekleniyor.</div>}
  {inventory?.pendingControlScan && <p className="managed-refresh-note">İşlem sonrası uygulama durumları ve önizlemeler yenileniyor…</p>}
  <div className="managed-list">{visible.map(app=><article className={`managed-row ${app.active===false?'managed-stopped':''}`} key={app.port}><button className="managed-preview" onClick={()=>onSelect(app)} aria-label={`${app.name} ayrıntılarını aç`}>{app.previewAt?<Image unoptimized width={160} height={95} src={url(`/previews/${app.port}?v=${encodeURIComponent(app.previewAt)}`)} alt={`${app.name} önizlemesi`} loading="lazy"/>:<Code2 size={32}/>}</button><div className="managed-app-info"><div className="managed-title"><code>:{app.port}</code><h3>{app.name}</h3></div><span className={`managed-state ${app.active===false?'stopped':app.httpApplicable!==false && (!app.status || app.status>=500)?'issue':'running'}`}><i className="status-dot"/>{app.active===false?'Kapalı · Başlatılabilir':app.httpApplicable!==false && (!app.status || app.status>=500)?'Açık · Yanıt kontrol edilmeli':'Ayakta'}</span><p className="managed-unit">{app.control?.label || app.process}{app.active!==false && app.pid?` · PID ${app.pid}`:''}</p><div className="managed-links"><Button variant="ghost" onClick={()=>onSelect(app)}>Ayrıntılar <ArrowUpRight size={13}/></Button><Button variant="ghost" onClick={()=>onHistory(app.port)}><History size={13}/>Günlük</Button>{(app.control?.affectedPorts?.length || 0)>1 && <span title={app.control?.affectedPorts?.map(p=>`:${p}`).join(', ')}>{app.control?.affectedPorts?.length} port birlikte yönetilir</span>}</div></div><ControlActions app={app} inventory={inventory} busy={busy} onAction={onAction}/></article>)}</div>
  {!visible.length && !inventory?.controlError && <div className="log-empty"><Settings2 size={30}/><strong>{inventory?.scannedAt?'Bu filtrede yönetilebilir uygulama yok.':'Kontrol bilgileri yükleniyor…'}</strong><p>Çalışan ve kapalı kayıtlı uygulamalar bu listede yer alır.</p>{(query || filter!=='all') && <Button variant="outline" onClick={()=>{setQuery('');setFilter('all');}}>Filtreleri temizle</Button>}</div>}
  <div className="managed-footer"><span>{visible.length} / {managed.length} yönetilebilir uygulama</span><p>Kapattığınız uygulama listede kalır. Çalışan uygulamada Durdur / Yeniden başlat, kapalı uygulamada Başlat etkinleşir.</p></div></section>;
}
