'use client';
import { useState } from 'react';
import { Activity, ArrowDownUp, ArrowUpRight, Bookmark, Boxes, CalendarClock, CircleHelp, Code2, Globe2, Grid2X2, History, LockKeyhole, Maximize2, RefreshCw, Search, Star, Terminal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import Image from 'next/image';
import ControlActions from './control-actions';
import { useTarget } from './target-context';
import type { App, ControlAction, Inventory } from './types';
const time = (v: string | null | undefined) => v ? new Date(v).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' }) : '—';
const statusLabel = (a: App) => a.networkState==='unknown' && a.active!==false ? 'Erişim belirsiz · Son kayıt' : a.active===false ? 'Kapalı' : a.httpApplicable===false ? 'Ayakta · Dinliyor' : !a.status ? 'Açık · Yanıt yok' : a.status>=500 ? `Açık · HTTP ${a.status}` : a.status===401 || a.status===403 ? 'Ayakta · Giriş gerekli' : a.status===404 ? 'Ayakta · Kök yol yok' : 'Ayakta';
const tone = (a: App) => a.networkState==='unknown' && a.active!==false ? 'amber' : a.active===false ? 'gray' : a.httpApplicable===false ? 'green' : !a.status || a.status >= 500 ? 'red' : 'green';
export function ServicePreview({ app, large = false, onClick }: { app: App; large?: boolean; onClick?: () => void }) {
 const {url}=useTarget();
  const [failedSource,setFailedSource]=useState<string|null>(null);const failed=!!app.previewAt && failedSource===app.previewAt;
  const content = app.previewAt && !failed ? <Image unoptimized width={1280} height={760} src={url(`/previews/${app.port}?v=${encodeURIComponent(app.previewAt)}`)} alt={`${app.name} uygulamasının ekran görüntüsü`} loading="lazy" onError={() => setFailedSource(app.previewAt || null)} /> : <div className={`service-preview ${app.kind === 'web' ? '' : 'api-preview'}`}><div className="service-preview-top"><i /><i /><i /><span>{app.kind === 'web' ? 'UYGULAMA ÖNİZLEMESİ' : 'SERVİS YANITI'}</span></div><div className="service-symbol">{app.kind === 'web' ? <Globe2 size={31} /> : <Code2 size={31} />}</div><div className="endpoint"><span>{app.protocol.toUpperCase()}</span> :{app.port}{app.path}</div><div className="service-caption">{app.active===false ? 'Port kapalı · Son kayıt korunuyor' : app.kind === 'web' ? app.previewError ? 'Ekran görüntüsü alınamadı' : 'Ekran görüntüsü hazırlanıyor' : app.status ? `HTTP ${app.status} · ${statusLabel(app)}` : app.httpApplicable===false ? 'Port açık · '+(app.transports?.join(' / ').toUpperCase() || app.protocol.toUpperCase())+' servisi' : 'Port açık · HTTP yanıtı yok'}</div></div>;
  return onClick ? <button className="preview" onClick={onClick} aria-label={`${app.name} önizlemesini büyüt`}>{content}<span className="preview-zoom"><Maximize2 size={15} /> Önizle</span></button> : <div className={`preview ${large ? 'preview-large' : ''}`}>{content}</div>;
}

export default function PortInventory({inventory,busy:controlBusy,onAction,onSelect,onHistory,onAnnotate,onMessage,onRefresh}:{
 inventory:Inventory|null;busy:boolean;onAction:(app:App,action:ControlAction)=>void;onSelect:(app:App)=>void;
 onHistory:(port?:number|null)=>void;onAnnotate:(app:App)=>void;onMessage:(message:string)=>void;onRefresh:()=>Promise<void>;
}){
 const {api,url}=useTarget();
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('port');
 const [favoriteBusy,setFavoriteBusy]=useState<number|null>(null),[actionPending,setActionPending]=useState(false);
 const apps=inventory?.apps || [],activeApps=apps.filter(a=>a.active!==false);
 const web=activeApps.filter(a=>a.kind==='web').length,internal=activeApps.filter(a=>a.internal).length;
 const responding=activeApps.filter(a=>a.networkState!=='unknown' && (a.httpApplicable===false || (a.status && a.status<500))).length;
 const problem=(app:App)=>app.active===false?!!app.annotation?.expectedUp:app.networkState==='unknown' || app.httpApplicable!==false && (!app.status || app.status>=500);
 const visible=apps.filter(a=>(filter==='all' || (filter==='favorites'?a.annotation?.favorite:filter==='closed'?a.active===false:filter==='issues'?problem(a):filter==='web'?a.kind==='web' && a.active!==false:filter==='internal'?a.internal && a.active!==false:a.kind!=='web' && a.active!==false)) && `${a.name} ${a.port} ${a.directory} ${a.annotation?.note || ''} ${a.annotation?.tags.join(' ') || ''}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'tr'):sort==='issues'?Number(problem(b))-Number(problem(a)) || a.port-b.port:sort==='recent'?new Date(b.firstSeen || 0).getTime()-new Date(a.firstSeen || 0).getTime():a.port-b.port);
 const controls=(app:App)=><ControlActions app={app} inventory={inventory} busy={controlBusy} onAction={onAction}/>;
 async function favorite(app:App){setFavoriteBusy(app.port);try{await api(`/apps/${app.port}/annotation`,{method:'PATCH',body:JSON.stringify({favorite:!app.annotation?.favorite})});await onRefresh();}catch(e){onMessage((e as Error).message);}finally{setFavoriteBusy(null);}}
 async function run(path:string){setActionPending(true);try{await api(path,{method:'POST',body:'{}'});await onRefresh();}catch(e){onMessage((e as Error).message);}finally{setActionPending(false);}}
 return <div className="desktop-port-inventory">
<section className="stats" aria-label="Port özeti"><div className="stat"><div><span>Kullanımdaki port</span><strong>{inventory?.scannedAt ? activeApps.filter(a=>a.networkState!=='unknown').length : '—'}<small>/{inventory ? inventory.end-inventory.start+1 : 65535}</small></strong></div><span className="stat-icon"><Boxes /></span><div className="stat-note">{inventory?.networkOnly?'Ağdan erişilen TCP portları':'Dinleyen TCP / UDP portları'}</div></div><div className="stat"><div><span>Web uygulaması</span><strong>{inventory?.scannedAt ? web.toString().padStart(2,'0') : '—'}</strong></div><span className="stat-icon"><Globe2 /></span><div className="stat-note"><span className="status-dot green" /> Ekran görüntüsüyle önizleme</div></div><div className="stat"><div><span>API & diğer servisler</span><strong>{inventory?.scannedAt ? (activeApps.length-web).toString().padStart(2,'0') : '—'}</strong></div><span className="stat-icon"><Terminal /></span><div className="stat-note">Servis bilgileriyle görüntüleme</div></div><div className="stat"><div><span>Ayakta / açık port</span><strong>{inventory?.scannedAt ? responding : '—'}<small>/{activeApps.length}</small></strong></div><span className="stat-icon green-icon"><Activity /></span><div className="stat-note">{apps.length-activeApps.length} kapalı · {internal} iç ağ servisi</div></div></section>
  <section className="insights-strip" aria-label="Denetim özeti"><Button variant="ghost" className={inventory?.insights?.issues?'needs-attention':''} onClick={()=>setFilter('issues')}><Activity size={17}/><strong>{inventory?.insights?.issues || 0}</strong> uygulama incelenmeli</Button><span>Son 24 saat <b>{inventory?.insights?.opened24h || 0}</b> açılma · <b>{inventory?.insights?.closed24h || 0}</b> kapanma</span><Button variant="ghost" onClick={()=>onHistory()}><History size={15}/>{inventory?.insights?.failed24h || 0} başarısız işlem <ArrowUpRight size={14}/></Button></section>
  <section className="audit-strip"><span className="audit-icon"><CalendarClock size={19} /></span><div><strong>Günlük port denetimi</strong><span>Her gece <b>00.00</b> · Türkiye saati <span className="audit-divider">/</span> Yeni ve kapanan portlar günlüğe kaydedilir.</span></div><Button variant="ghost" onClick={() => onHistory()}>Günlüğü görüntüle <ArrowUpRight size={15} /></Button></section><section className="applications" aria-label="Uygulamalar"><div className="section-heading"><h2>Uygulamalar <span>{apps.length}</span></h2><span className="scan-indicator"><span className={`status-dot ${inventory?.capturing ? 'amber' : 'green'}`} />{inventory?.capturing ? 'Önizlemeler hazırlanıyor…' : `Son tarama · ${time(inventory?.scannedAt)}`}</span></div><div className="toolbar"><div className="filter-group" aria-label="Uygulama filtreleri">{[{key:'all',label:'Tümü',icon:Grid2X2},{key:'favorites',label:'Favoriler',icon:Star},{key:'web',label:'Web uygulamaları',icon:Globe2},{key:'api',label:'API & servisler',icon:Code2},{key:'closed',label:'Kapalı',icon:LockKeyhole},{key:'issues',label:'Sorunlu',icon:Activity}].map(({key,label,icon:Icon}) => <Button key={key} variant="ghost" className={filter===key ? 'filter active' : 'filter'} aria-pressed={filter===key} onClick={() => setFilter(key)}><Icon />{label}</Button>)}</div><div className="search-tools"><div className="search-field"><Search size={16} /><Input aria-label="Uygulama adı veya port ara" placeholder="Ad, port, etiket veya not ara…" value={query} onChange={e => setQuery(e.target.value)} />{query && <button aria-label="Aramayı temizle" onClick={() => setQuery('')}><X size={14} /></button>}</div><Select value={sort} onValueChange={value=>{if(value)setSort(value);}} items={{port:'Port sırası',name:'Ada göre',issues:'Sorunlar önce',recent:'Yeni eklenenler'}}><SelectTrigger aria-label="Uygulamaları sırala" className="sort-picker"><ArrowDownUp size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="port">Port sırası</SelectItem><SelectItem value="name">Ada göre</SelectItem><SelectItem value="issues">Sorunlar önce</SelectItem><SelectItem value="recent">Yeni eklenenler</SelectItem></SelectContent></Select></div></div>
  {inventory?.controlError && <div className="notice error-notice"><CircleHelp size={17}/><span>{inventory.controlError}</span></div>}
  {inventory?.previewError && <div className="notice"><CircleHelp size={17} /><span>{inventory.previewError}</span></div>}
  <div className="app-grid">{visible.map(app => <article className={`app-card ${app.active===false ? 'closed-card' : ''}`} key={app.port}><div className="card-browser"><span className="browser-dots"><i /><i /><i /></span><span><LockKeyhole size={11} />{inventory?.host}:{app.port}</span><span className="protocol-label">{app.protocol.toUpperCase()}</span></div><ServicePreview app={app} onClick={() => onSelect(app)} /><div className="card-content"><div className="card-title-row"><span className={`app-icon ${app.kind==='web' ? '' : 'api-icon'}`}>{app.kind==='web' ? <Globe2 size={19} /> : <Code2 size={19} />}</span><div><h3 title={app.name}>{app.name}</h3><div className="card-type">{app.kind==='web' ? 'Web uygulaması' : app.kind==='api' ? 'API servisi' : 'Arka plan servisi'}{app.internal && <><span>·</span><LockKeyhole size={11} /> İç ağ</>}</div></div><button className={`favorite-toggle ${app.annotation?.favorite?'is-favorite':''}`} disabled={favoriteBusy!==null} aria-label={`${app.name} ${app.annotation?.favorite?'favorilerden çıkar':'favorilere ekle'}`} aria-pressed={!!app.annotation?.favorite} onClick={()=>void favorite(app)}><Star size={17} fill={app.annotation?.favorite?'currentColor':'none'}/></button><span className="port-badge">:{app.port}</span></div>{(!!app.annotation?.tags.length || app.annotation?.expectedUp) && <div className="card-tags">{app.annotation?.tags.map(tag=><button key={tag} onClick={()=>setQuery(tag)}>{tag}</button>)}{app.annotation?.expectedUp && <span className={app.active===false?'expected-down':''}>Sürekli çalışmalı</span>}</div>}<div className="card-bottom"><span className={`app-status ${tone(app)}`}><span className={`status-dot ${tone(app)}`} />{statusLabel(app)}</span><div><Button variant="ghost" size="icon" onClick={() => onSelect(app)} aria-label={`${app.name} ayrıntıları`}><Maximize2 /></Button>{app.openUrl ? <a className="open-link" href={url(`/apps/${app.port}/open`)} target="_blank" rel="noopener noreferrer">Aç <ArrowUpRight size={16} /></a> : <span className="no-open">{app.active===false ? 'Kapalı' : app.httpApplicable===false ? 'Sistem servisi' : 'Yalnızca yerel'}</span>}</div></div>{controls(app)}<Button variant="ghost" className="card-note-button" onClick={()=>onAnnotate(app)}><Bookmark size={13}/>{app.annotation?.note?'Port notunu görüntüle':'Port notu ekle'}</Button></div></article>)}</div>
  {!visible.length && <div className="empty-state"><Search size={30} /><h3>{inventory?.scanning ? 'Sunucudaki uygulamalar taranıyor' : query || filter!=='all' ? 'Eşleşen uygulama bulunamadı' : 'Henüz bir servis bulunamadı'}</h3><p>{inventory?.scanning ? 'Portlar ve uygulama yanıtları kısa süre içinde burada görünecek.' : 'Aramanızı değiştirebilir veya portları yeniden tarayabilirsiniz.'}</p>{(query || filter!=='all') && <Button variant="outline" onClick={() => {setQuery('');setFilter('all');}}>Filtreleri temizle</Button>}</div>}
  <div className="list-footer"><span>{visible.length} / {apps.length} uygulama gösteriliyor</span><Button variant="ghost" disabled={inventory?.capturing || !apps.length || actionPending} onClick={() => run('/previews')}><RefreshCw size={14} />Önizlemeleri yenile</Button></div></section></div>;
}
