/** Entirely invented presentation data. This module never reads a host or a file. */
export const DEMO_SERVER_IDS = Object.freeze(['demo-linux', 'demo-windows']);
export const DEMO_NOTICE = 'Demo görünümü: tüm sunucular, uygulamalar ve ölçümler temsilidir. Gerçek bağlantı kurulmaz.';
const GiB = 1024 ** 3;
const MiB = 1024 ** 2;
const escapeXml = value => String(value).replace(/[<>&"']/g, char => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' })[char]);
const appNames = { 3000: 'Atlas Portal', 8080: 'Atlas API', 5432: 'PostgreSQL', 6379: 'Redis', 11434: 'Model Studio', 8088: 'Insight Reports', 8443: 'Workspace Hub', 5050: 'Automation API' };

export function demoPreviewSvg(serverId, port) {
  const title = escapeXml(appNames[Number(port)] || 'Örnek uygulama');
  const windows = serverId === 'demo-windows';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="760" viewBox="0 0 1280 760"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#11b8aa"/><stop offset="1" stop-color="#1580eb"/></linearGradient></defs><rect width="1280" height="760" fill="#f3f7fa"/><rect width="244" height="760" fill="#122a37"/><circle cx="45" cy="48" r="14" fill="url(#g)"/><text x="74" y="57" fill="white" font-size="24" font-family="sans-serif" font-weight="700">${title}</text><text x="28" y="130" fill="#88a6b7" font-size="15" font-family="sans-serif">ÇALIŞMA ALANI</text>${['Genel bakış','Projeler','Raporlar','Ekip'].map((label, index) => `<rect x="16" y="${155 + index * 62}" width="210" height="48" rx="10" fill="${index === 0 ? '#244656' : '#122a37'}"/><text x="35" y="${186 + index * 62}" fill="${index === 0 ? '#74e4d8' : '#bbcdd6'}" font-size="19" font-family="sans-serif">${label}</text>`).join('')}<text x="286" y="63" fill="#213e51" font-size="31" font-family="sans-serif" font-weight="700">Her şey bir arada.</text><text x="286" y="96" fill="#708493" font-size="17" font-family="sans-serif">${windows ? 'Windows' : 'Linux'} · örnek uygulama önizlemesi</text><rect x="1070" y="37" width="165" height="35" rx="17" fill="#dbf5ed"/><text x="1097" y="61" fill="#137e66" font-size="15" font-family="sans-serif">TEMSİLİ DEMO</text>${[['Aktif projeler','24'],['Tamamlanan','128'],['Ekip üyeleri','12']].map((item,index)=>`<rect x="${286+index*319}" y="133" width="297" height="129" rx="17" fill="white"/><text x="${310+index*319}" y="171" fill="#708493" font-size="17" font-family="sans-serif">${item[0]}</text><text x="${310+index*319}" y="226" fill="#213e51" font-size="42" font-weight="700" font-family="sans-serif">${item[1]}</text>`).join('')}<rect x="286" y="288" width="935" height="294" rx="17" fill="white"/><text x="310" y="328" fill="#213e51" font-size="21" font-family="sans-serif">Haftalık görünüm</text><path d="M320 516 L442 468 L558 485 L679 414 L798 430 L918 369 L1040 389 L1180 346 L1180 548 L320 548Z" fill="#e6f7f4"/><path d="M320 516 L442 468 L558 485 L679 414 L798 430 L918 369 L1040 389 L1180 346" fill="none" stroke="#14aaa4" stroke-width="5" stroke-linecap="round"/><rect x="286" y="608" width="935" height="102" rx="17" fill="white"/><circle cx="331" cy="660" r="19" fill="#dcf4eb"/><text x="371" y="655" fill="#213e51" font-size="19" font-family="sans-serif">Bu arayüz demo için oluşturuldu.</text><text x="371" y="684" fill="#708493" font-size="16" font-family="sans-serif">Gerçek uygulama veya sunucu verisi içermez.</text></svg>`;
}

export function demoPreviewUrl(serverId, port) {
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(demoPreviewSvg(serverId, port));
}

const capacity = (total, used, reserved = 0) => ({ totalBytes: total * GiB, usedBytes: used * GiB, freeBytes: (total - used) * GiB, availableBytes: (total - used - reserved) * GiB, reservedBytes: reserved * GiB, percent: Math.round(used / total * 1000) / 10 });

function makeServer(index, now) {
  const windows = index === 1;
  const id = DEMO_SERVER_IDS[index], host = `192.0.2.${10 + index * 10}`, hostname = windows ? 'demo-workspace' : 'demo-platform';
  const base = windows ? '/C:/Apps' : '/srv';
  const specs = windows ? [[8443, 'Workspace Hub', 'web', 'workspace'], [5050, 'Automation API', 'api', 'automation'], [8088, 'Insight Reports', 'web', 'reports']] : [[3000, 'Atlas Portal', 'web', 'atlas'], [8080, 'Atlas API', 'api', 'atlas'], [5432, 'PostgreSQL', 'service', 'database'], [6379, 'Redis', 'service', 'cache'], [11434, 'Model Studio', 'api', 'models']];
  const connection = { id, host, name: windows ? 'Workspace · Windows Demo' : 'Platform · Linux Demo', hostname, platform: windows ? 'windows' : 'linux', port: 22, username: 'demo-operator', authType: 'password', fingerprint: 'Demo: gerçek SSH kimliği yok', status: 'ready', phase: 'ready', message: DEMO_NOTICE, active: specs.length, updatedAt: now, configRevision: 0, capabilities: { inventory: true, resources: true, storage: true, files: true, control: false, versions: true, models: true } };
  const apps = specs.map(([port, name, kind, project], position) => ({ port, name, title: name, kind, directory: `${base}/${project}`, filesPath: `${base}/${project}`, process: kind === 'service' ? name.toLowerCase() : windows ? 'dotnet' : 'node', pid: 2100 + position, addresses: ['127.0.0.1'], internal: true, protocol: port === 8443 ? 'https' : kind === 'service' ? 'tcp' : 'http', transports: ['tcp'], path: '/', status: kind === 'service' ? null : 200, httpApplicable: kind !== 'service', latency: 8 + position * 7, active: true, health: 'healthy', networkState: 'open', firstSeen: new Date(Date.parse(now) - 86400000).toISOString(), lastSeen: now, previewAt: kind !== 'service' ? now : undefined, openUrl: undefined, annotation: { displayName: '', note: position === 0 ? 'Demo için hazırlanmış örnek uygulama.' : '', favorite: position === 0, expectedUp: true, tags: [windows ? 'Windows' : 'Linux', 'demo'], revision: 0 }, control: { canStart: false, canStop: false, canRestart: false, active: true, reason: 'Demo modunda gerçek servis işlemi yapılamaz.' }, project: { id: project, name: project === 'atlas' ? 'Atlas Suite' : name, directory: `${base}/${project}`, primaryPort: project === 'atlas' ? 3000 : port, system: kind === 'service' }, modelConnections: port === 3000 ? [{ endpoint: 'http://192.0.2.10:11434', model: 'Example Chat 8B', role: 'Demo asistanı', scope: 'project', evidence: [{ kind: 'config', key: 'DEMO_MODEL', file: 'demo.config.json' }] }] : [], modelDiscovery: { status: port === 3000 ? 'found' : 'not-found', checkedAt: now } }));
  const volumes = windows ? [{ id: 'demo-c', source: 'C:', mount: '/C:', filesystem: 'NTFS', ...capacity(512, 174) }, { id: 'demo-d', source: 'D:', mount: '/D:', filesystem: 'NTFS', ...capacity(1024, 386) }] : [{ id: 'demo-root', source: '/dev/demo-root', mount: '/', filesystem: 'ext4', ...capacity(256, 92, 12) }, { id: 'demo-data', source: '/dev/demo-data', mount: '/srv', filesystem: 'ext4', ...capacity(1024, 438, 32) }];
  const total = volumes.reduce((sum, item) => sum + item.totalBytes / GiB, 0), used = volumes.reduce((sum, item) => sum + item.usedBytes / GiB, 0), reserved = volumes.reduce((sum, item) => sum + item.reservedBytes / GiB, 0);
  const storage = { available: true, sampledAt: now, hostname, summary: { ...capacity(total, used, reserved), volumeCount: volumes.length }, volumes };
  const inventory = { serverId: id, demo: true, host, hostname, platform: connection.platform, capabilities: connection.capabilities, mode: 'demo', apps, scannedAt: now, scanning: false, capturing: false, error: null, previewError: null, stale: false, start: 1, end: 65535, unread: 2, nextAuditAt: new Date(Date.parse(now) + 86400000).toISOString(), lastDailyAuditDay: now.slice(0, 10), insights: { issues: 0, expectedDown: 0, favorites: 1, opened24h: 1, closed24h: 0, failed24h: 0 } };
  const resources = { available: true, demo: true, host, hostname, sampledAt: Date.parse(now), sampleSeconds: 2, portCount: apps.length, system: { cpuPercent: windows ? 18.2 : 26.4, cpuCount: windows ? 8 : 16, memory: { totalBytes: (windows ? 32 : 64) * GiB, usedBytes: (windows ? 11 : 23) * GiB, percent: windows ? 34.4 : 35.9, swapTotalBytes: 4 * GiB, swapUsedBytes: 0 }, disk: { ...storage.summary, scope: 'server', mount: null, available: true }, uptimeSeconds: 86400 * 12 + 14400, loadAverage: [1.2, 1.4, 1.1], processCount: windows ? 134 : 96 }, applications: apps.map((app, position) => ({ id: `pid:${app.pid}`, ports: [app.port], listenerPids: [app.pid], pids: [app.pid], processNames: [app.process], transports: ['tcp'], cpuPercent: 2.4 + position * 1.8, memoryBytes: (180 + position * 90) * MiB, memoryPercent: 0.7 + position * 0.2, readBytesPerSecond: (position + 1) * 24000, writeBytesPerSecond: (position + 1) * 8000, scope: 'process-tree' })) };
  const processes = apps.map((app, position) => ({ pid: app.pid, parentPid: 1, name: app.process, user: 'demo-operator', state: windows ? 'Running' : 'S', cpuPercent: 2.4 + position * 1.8, memoryBytes: (180 + position * 90) * MiB, startedAt: new Date(Date.parse(now) - 3600000).toISOString(), token: null, canTerminate: false, reason: 'Temsili demo süreci; sonlandırma kapalıdır.' }));
  const services = apps.slice(0, 3).map((app, position) => ({ name: windows ? `DemoService${position + 1}` : `demo-app-${position + 1}.service`, displayName: `${app.name} · Demo`, description: 'Önizleme için üretilmiş örnek servis; gerçek sunucuya bağlı değildir.', state: position === 2 ? (windows ? 'Stopped' : 'inactive') : (windows ? 'Running' : 'active'), subState: position === 2 ? 'dead' : 'running', startup: windows ? 'Auto' : 'enabled', pid: position === 2 ? null : app.pid, token: null, actions: [], reason: 'Demo servisleri yalnız görüntülenir.', canLogs: !windows, lab: false, dependencies: [], dependents: [] }));
  storage.topology = { available: true, partial: false, devices: volumes.flatMap((volume, position) => [
    { id: `demo-disk-${position}`, name: windows ? `Disk ${position} · Demo` : `demo-disk-${position}`, kind: 'disk', sizeBytes: volume.totalBytes, model: 'Synthetic demo disk', partitionStyle: 'GPT', parentIds: [], volumeIds: [], readBytesPerSecond: (position + 1) * MiB, writeBytesPerSecond: (position + 1) * MiB / 2 },
    { id: `demo-partition-${position}`, name: `${volume.source} · Demo`, kind: 'partition', sizeBytes: volume.totalBytes, parentIds: [`demo-disk-${position}`], volumeIds: [volume.id], readBytesPerSecond: null, writeBytesPerSecond: null },
  ]) };
  const overview = { version: 1, demo: true, available: true, status: 'online', extended: true, serverId: id, host, hostname, sampledAt: Date.parse(now), platform: connection.platform, os: windows ? 'Windows · Demo' : 'Linux · Demo', kernel: 'Demo', addresses: [host], ...resources.system, cpuTemperatureC: null,
    disks: storage.topology.devices.filter(device => device.kind === 'disk').map(({ name, readBytesPerSecond, writeBytesPerSecond }) => ({ name, readBytesPerSecond, writeBytesPerSecond })),
    network: [{ name: 'Demo adapter', readBytesPerSecond: 2 * MiB, writeBytesPerSecond: MiB }], topProcesses: processes };
  const uniqueApps = [...new Map(apps.map(app => [app.project.id, app])).values()];
  const files = {};
  const directory = (path, bytes = 0) => { files[path] = { path, name: path.split('/').filter(Boolean).at(-1) || '/', kind: 'directory', size: bytes, content: null }; };
  const file = (path, content) => { files[path] = { path, name: path.split('/').at(-1), kind: 'file', size: new TextEncoder().encode(content).length, content }; };
  directory('/');
  if (windows) { directory('/C:'); directory('/D:'); directory('/D:/Archive'); }
  directory(base);
  for (const app of uniqueApps) {
    directory(app.directory, (12 + app.port % 37) * GiB);
    directory(`${app.directory}/docs`, 2 * MiB);
    file(`${app.directory}/README.md`, `# ${app.project.name}\n\nBu dosya ViiOS demosu için hazırlanmış örnek içeriktir.\nGerçek bir sunucuya bağlı değildir.\n\n- Uygulama görünümü\n- Depolama ve kaynaklar\n- Dosya gezgini\n`);
    file(`${app.directory}/demo.config.json`, JSON.stringify({ application: app.project.name, environment: 'demo', synthetic: true }, null, 2));
    file(`${app.directory}/docs/guide.txt`, 'ViiOS Demo\n\nÖrnek klasörleri gezebilir, uygulamaları ve kaynak panellerini inceleyebilirsiniz.\nGerçek dosya yükleme, sunucu bağlantısı ve parola kaydı bu demoda kapalıdır.\n');
  }
  const events = [{ id: id + '-event-1', type: 'opened', port: apps[0].port, name: apps[0].name, message: 'Örnek uygulama demo envanterine eklendi.', at: now, notify: true, read: false, previewAt: null }, { id: id + '-event-2', type: 'daily_audit', port: null, name: null, message: 'Temsili günlük kontrol tamamlandı; tüm örnek uygulamalar hazır.', at: new Date(Date.parse(now) - 3600000).toISOString(), notify: true, read: false, previewAt: null }];
  const models = [{ id: id + '-chat', name: 'Example Chat 8B · Demo', family: 'Örnek', kind: 'language', host, runtime: 'Ollama', status: 'running', parameterSize: '8B', quantization: 'Q4', contextLength: 8192, sizeBytes: 4.8 * GiB, endpoint: `http://${host}:11434`, paths: [`${base}/models/example-chat.gguf`], applications: [{ name: apps[0].name, port: apps[0].port }], evidence: [{ kind: 'config', source: 'ViiOS Demo', detail: 'Bu model ve ölçümler tanıtım amacıyla üretilmiştir; gerçek çıkarım yapılmaz.' }], checkedAt: now }, { id: id + '-embedding', name: 'Example Embedding · Demo', family: 'Örnek', kind: 'embedding', host, runtime: 'Model dosyaları', status: 'installed', parameterSize: '137M', quantization: 'F16', contextLength: 512, sizeBytes: 274 * MiB, endpoint: null, paths: [`${base}/models/example-embedding`], applications: [], evidence: [{ kind: 'disk', source: 'ViiOS Demo', detail: 'Temsili model dosyası.' }], checkedAt: now }];
  const catalog = { demo: true, scanning: false, stale: false, scannedAt: now, lastAttemptAt: now, error: null, warnings: [DEMO_NOTICE], models, hosts: [{ id, name: connection.name, host, status: 'online', gpus: [{ name: 'Örnek GPU · Demo', memoryTotalMiB: 24576, memoryUsedMiB: 6144, utilizationPercent: 28 }], error: null }], coverage: { hostsChecked: 1, endpointsChecked: 1, filesChecked: 2, notes: [DEMO_NOTICE] } };
  const projects = uniqueApps.filter(app => !app.project.system).map(app => ({ id: app.project.id, name: app.project.name, path: app.directory, existing: true }));
  const commits = [{ id: 'a'.repeat(40), short: 'aaaaaaa', date: now, message: 'Örnek arayüz eklendi', author: 'Demo ekip', refs: 'HEAD -> main', number: 2 }, { id: 'b'.repeat(40), short: 'bbbbbbb', date: new Date(Date.parse(now) - 86400000).toISOString(), message: 'Demo projesi oluşturuldu', author: 'Demo ekip', refs: '', number: 1 }];
  return { connection, inventory, resources, overview, processes, services, storage, files, base, projects, commits, events, catalog, desktop: { version: 1, revision: 0, dock: null, desktop: null }, appUsage: { status: 'ready', scannedAt: now, partial: false, applications: uniqueApps.map(app => ({ id: app.project.id, name: app.project.name, path: app.directory, bytes: files[app.directory].size })) } };
}

export function createFixtures(now = new Date().toISOString()) {
  const servers = Object.fromEntries(DEMO_SERVER_IDS.map((id, index) => [id, makeServer(index, now)]));
  return { now, servers, team: { revision: 0, people: [{ id: 'demo-platform-team', name: 'Platform ekibi · Demo' }, { id: 'demo-design-team', name: 'Tasarım ekibi · Demo' }], assignments: [{ id: 'demo-assignment', serverId: DEMO_SERVER_IDS[0], projectId: 'atlas', projectName: 'Atlas Suite', projectPath: '/srv/atlas', personId: 'demo-platform-team', role: 'Uygulama yönetimi', serviceKey: null, serviceLabel: null }] } };
}
